// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBieDl8s31gWm3Pm4k4m1xiaGbvIPmj8Qg',
    appId: '1:352029847784:web:cc3a96ffc54a98dbfed95d',
    messagingSenderId: '352029847784',
    projectId: 'smarthealth-60fc1',
    authDomain: 'smarthealth-60fc1.firebaseapp.com',
    storageBucket: 'smarthealth-60fc1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFvRGXU2cTuipnudmiFi4j3VoYUrKScEs',
    appId: '1:352029847784:android:5a26ce49aa336cadfed95d',
    messagingSenderId: '352029847784',
    projectId: 'smarthealth-60fc1',
    storageBucket: 'smarthealth-60fc1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRbWc2qKqpUue0I2dmkDYm_j0MFcPhEzg',
    appId: '1:352029847784:ios:a15df6c2a22570fcfed95d',
    messagingSenderId: '352029847784',
    projectId: 'smarthealth-60fc1',
    storageBucket: 'smarthealth-60fc1.firebasestorage.app',
    iosBundleId: 'com.example.smartHealthFoodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRbWc2qKqpUue0I2dmkDYm_j0MFcPhEzg',
    appId: '1:352029847784:ios:a15df6c2a22570fcfed95d',
    messagingSenderId: '352029847784',
    projectId: 'smarthealth-60fc1',
    storageBucket: 'smarthealth-60fc1.firebasestorage.app',
    iosBundleId: 'com.example.smartHealthFoodApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBieDl8s31gWm3Pm4k4m1xiaGbvIPmj8Qg',
    appId: '1:352029847784:web:f6d5fdacee479093fed95d',
    messagingSenderId: '352029847784',
    projectId: 'smarthealth-60fc1',
    authDomain: 'smarthealth-60fc1.firebaseapp.com',
    storageBucket: 'smarthealth-60fc1.firebasestorage.app',
  );
}
